title: Michael C. Kopreski
logo: /assets/img/surfaces.png
theme: jekyll-theme-minimal
url: https://mckopreski.github.io
plugins:
  - jekyll-sitemap

defaults:
  -
    scope:
      path: "test"
    values:
      sitemap: false
  -
    scope:
      path: "sa"
    values:
      sitemap: false
  -
    scope:
      path: "assets"
    values:
      sitemap: false

